name: .deb packaging

on:
  workflow_dispatch:

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: arm32v7
            distro: ubuntu16.04
          - arch: arm32v7
            distro: ubuntu18.04
          - arch: arm32v7
            distro: ubuntu22.04
          - arch: arm32v7
            distro: ubuntu24.04
          - arch: arm32v7
            distro: ubuntu24.10            
          - arch: arm32v7
            distro: bullseye
          - arch: arm32v7
            distro: bookworm      
          - arch: aarch64
            distro: ubuntu18.04
          - arch: aarch64
            distro: ubuntu20.04
          - arch: aarch64
            distro: ubuntu22.04            
          - arch: aarch64
            distro: ubuntu24.04
          - arch: aarch64
            distro: ubuntu24.10            
          - arch: aarch64
            distro: buster
          - arch: aarch64
            distro: bullseye
          - arch: aarch64
            distro: bookworm
          - arch: amd64
            distro: buster
          - arch: i386
            distro: buster
          - arch: amd64
            distro: bullseye
          - arch: amd64
            distro: bookworm
          - arch: i386
            distro: bullseye
          - arch: i386
            distro: bookworm
          - arch: amd64
            distro: ubuntu16.04
          - arch: i386
            distro: ubuntu16.04
          - arch: amd64
            distro: ubuntu18.04
          - arch: i386
            distro: ubuntu18.04
          - arch: amd64
            distro: ubuntu20.04
          - arch: amd64
            distro: ubuntu22.04
          - arch: amd64
            distro: ubuntu24.04
          - arch: amd64
            distro: ubuntu24.10            

    steps:
      - uses: actions/checkout@v2.1.0

      - uses: allinurl/run-on-arch-action@master
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          # Not required, but speeds up builds
          githubToken: ${{ github.token }}
          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          # The shell to run commands with in the container
          shell: /bin/bash
          # Install some dependencies in the container.
          install: |
            case "${{ matrix.distro }}" in
              ubuntu*|jessie|stretch|buster|bullseye|bookworm)
                apt-get update && apt-get install -y ca-certificates wget curl lsb-release && apt-get clean all
                ;;
            esac
          # Produce a binary artifact and place it in the mounted volume
          run: |
            ls -lath "/artifacts"
            curl -O https://deb.goaccess.io/provision/provision.dpkg.sh
            chmod +x ./provision.dpkg.sh
            ./provision.dpkg.sh
            echo "Success!!"

      - name: Show the artifact
        run: |
          pwd
          ls -lath "${PWD}/artifacts"

      - name: Test deb package installation
        run: |
          # Download the test script from deb.goaccess.io
          curl -O https://deb.goaccess.io/provision/test-dpkg.sh
          chmod +x test-dpkg.sh
          # Find the generated deb package
          DEB_FILE=$(find "${PWD}/artifacts" -name "goaccess_*.deb")
          echo "Found deb package: $DEB_FILE"
          # Run the test script to install, verify, and uninstall the package
          ./test-dpkg.sh "$DEB_FILE"

      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package-${{ matrix.distro }}-${{ matrix.arch }}
          path: 'artifacts/*.deb'
          retention-days: 1
